### ISSUE TITLE
Proyecto práctico

### ISSUE THREAD

**Issue by Pakillo** [Rstats-courses/CursoR-AEET-2022#1]
Hola @ibartomeus @elequintero

Necesitamos diseñar el proyecto práctico a realizar por parejas. Se me ocurre que una posibilidad es que elijan alguna especie o grupos de especies, se descarguen y limpien datos de presencia de GBIF (con R, claro), los unan con otro tipo de datos (de traits, clima, ambiente, etc), hagan algún modelo, analicen, visualicen, y nos lo presenten todo el último día

Así practicarían tanto data management como visualización, análisis y presentación de resultados.

Caveats: probablemente deberían usar modelos espaciales, que no cubrimos en el curso... Una opción es que detecten ese problema (eg con DHARMa) y algunos se aventuren a corregirlo, otros simplemente lo detecten y sepan que es algo a mejorar. Sería una situación muy real de nuestro día a día, no?

Cómo lo veis? Otras ideas de proyectos?

**Comment by Pakillo** [comment]
Cada día podríamos dedicar entre 10 minutos y media hora a resolver problemas que encuentren durante el desarrollo del proyecto, tanto de análisis como de código. Puede ser muy instructivo echar un ojo al código e intentar mejorarlo etc. Como idealmente estarán trabajando en github es fácil tenerlo todo a la vista

**Comment by ibartomeus** [comment]
A mi ya sabes que me gusta la idea de que trasteen con datos reales. Quien quiera hacer algo a nivel de comunidad y no usar ocurrencias, podemos tener opción PREDICTS o acabo de encontrar esto: https://ecologicaldata.org/find-data

**Comment by elequintero** [comment]
Yo veo bien las dos opciones, así pueden elegir dependiendo de lo que más les interese. 

A parte, el otro día le comenté a Paco, ha salido un paquete nuevo con datos de seguimiento a largo plazo para utilizar en clases de estadística - https://lter.github.io/lterdatasampler/index.html. Lo bueno es que cada base de datos se presta a hacer distintos tipos de análisis (relaciones lineares, espaciales, temporales...). Lo único es que los datos ya están bastante limpios y no hay que complicarse la vida para descargarlos, así que no ofrece mucho data management. Pero bueno, por si hubiese menos tiempo, es otra opción.

¿O queréis dejar algo más cerrado con un guión para que todos hagan cosas parecidas?

**Comment by elequintero** [comment]
Igual el lter este es demasiado sencillo... 

He echado un ojo a la web que ha puesto Nacho y hay algunos dataset que no son localizables o no están digitalizados, pero poniendo como filtro "publicly available" hay muchos que son Data Papers de la ESA y que están bien. La opción GBIF es un poco más estructurada. A mí me parecen genial ambas, como veáis.

**Comment by ibartomeus** [comment]
Yo he usado PREDICTS y os aseguro que ahí hay para limpiar un buen rato, por si queremos usar solo una base de datos, Yo podría tener algo preparado para saber cuales son los principales problemas y como solucionarlos. Lo bueno es que se pueden calcular cosas a nivel de comunidad. Lo de lter podría ser una muy buena opción si hay alguien que vaya muy pez y vemos que le cuesta. Así hay tres opciones con tres plataformas: Gbif, predicts y Lter.

**Comment by Pakillo** [comment]
OK, gracias, así tenemos varias opciones para que elijan en función de sus intereses

**Comment by Pakillo** [comment]
Más opciones para elegir: alguna competición de Kaggle (https://www.kaggle.com/competitions) o DrivenData (https://www.drivendata.org/competitions/) 

O los datos de ManyAnalysts Ecology: https://osf.io/mn5aj/
