### ISSUE TITLE
Programa

### ISSUE THREAD

**Issue by Pakillo** [Rstats-courses/CursoR-AEET-2022#2]
Hola @ibartomeus @elequintero

Ya tenemos el [programa tentativo](https://github.com/Rstats-courses/CursoR-AEET-2022#programa-tentativo). He hecho algún cambio el viernes. Creo que necesitarán algo de tiempo para terminar el proyecto (desde el miércoles tarde que habrán estado trabajando en él). Idealmente se animen a presentarlo con Rmarkdown (diapos, html, whatever)
Entonces empezaríamos con GIS con R, luego tiempo de trabajo y por la tarde cerramos con las presentaciones (10 minutos por grupo ~ 2 horas)
Si alguno quiere preguntar sobre otros análisis podríamos aprovechar ese tiempo también
¿Qué os parece?

**Comment by ibartomeus** [comment]
Perfect!

**Comment by elequintero** [comment]
Hola! Gracias por añadirme al repo :) Es un honor participar en este curso. 
Yo lo veo genial, así tienen tiempo por la la mañana de dejar terminados sus proyectos, y aseguráis dar la clase de R-GIS antes de las presentaciones.

**Comment by Pakillo** [comment]
He añadido unos 30-60 minutos de functional programming (escribir funciones + iteraciones, ver https://r4ds.had.co.nz/functions.html & https://r4ds.had.co.nz/iteration.html). En principio el miércoles por la tarde
Creo que es importante que aprendan a escribir funciones y ejecutar algo repetidamente. No sólo mejora increíblemente la calidad del código sino que les abre la puerta a programar paquetes en el futuro etc

**Comment by Pakillo** [comment]
Creo que un reparto preliminar podría ser así:

@elequintero Tidy data + Data Manipulation (L), ggplot (M)

@ibartomeus Common-sense stats (L), Functional programming (X), Multivariate (J)

@Pakillo git (L), GLM (M), GLMM (X), Rmarkdown (J), R-GIS (V)

Aparte del tiempo de apoyo con los proyectos. 

¿Cómo lo veis? No queda mucho tiempo para trabajar en el proyecto ahora mismo, pero intentaremos meter algunos huecos

**Comment by ibartomeus** [comment]
Lo veo bien, el functional programming puedo intentar integrarlo con el proyecto... yo lo solia meter junto a los null models, lo acabamos de ver. Avisa a Leyre de las fechas tentativas!

**Comment by elequintero** [comment]
Estupendo, gracias Paco! Más pegado a la fecha os preguntaré bien por el modo de trabajo y por los todos temas que soléis tratar en tidy data y ggplot y para no dejarme nada y llevarlo bien preparado.
